"""Mechanical-design stack overview for the umbrella package.

## Introduction
Trace a lightweight mechanical-design workflow through the umbrella package
using packaged structural and humanitarian-product benchmarks.

## Technical Implementation
1. Load a small shortlist of mechanical-design problems from the packaged
   problem catalog and build a one-run umbrella study around a safe benchmark.
2. Export canonical artifacts and validate the resulting `events.csv` table.

## Expected Results
The script prints the wrapped module names, a short summary for each packaged
mechanical problem, and the artifact filenames generated by one successful
mechanical-design baseline study.
"""

from __future__ import annotations

import csv
import importlib
from pathlib import Path

dr = importlib.import_module("design_research")

MECHANICAL_PROBLEM_IDS = (
    "treadle_pump_ide_material_min",
    "battery_pack_18650_series_parallel_cost_min",
    "space_truss_span_mass_min",
)
DEMO_PROBLEM_ID = "treadle_pump_ide_material_min"
BASELINE_AGENT_ID = "SeededRandomBaselineAgent"
STUDY_ID = "mechanical_design_stack"
OUTPUT_DIR = Path("artifacts") / "examples" / STUDY_ID


def _problem_summary(problem_id: str) -> str:
    """Return one short summary line for a packaged mechanical problem."""
    problem = dr.problems.get_problem(problem_id)
    metadata = getattr(problem, "metadata", None)
    title = getattr(metadata, "title", problem_id)
    kind = getattr(getattr(metadata, "kind", None), "value", "unknown")
    return f"{problem_id}: {title} [{kind}]"


def _build_study() -> object:
    """Build one small umbrella study around a packaged mechanical problem."""
    return dr.experiments.Study(
        study_id=STUDY_ID,
        title="Mechanical Design Stack",
        description=(
            "Run one deterministic mechanical-design baseline through the umbrella package "
            "using packaged problems, a public agent, and canonical analysis exports."
        ),
        output_dir=OUTPUT_DIR,
        problem_ids=(DEMO_PROBLEM_ID,),
        agent_specs=(BASELINE_AGENT_ID,),
        outcomes=(
            dr.experiments.OutcomeSpec(
                name="primary_outcome",
                source_table="runs",
                column="primary_outcome",
                aggregation="mean",
                primary=True,
            ),
        ),
        run_budget=dr.experiments.RunBudget(replicates=1, parallelism=1, max_runs=1),
        primary_outcomes=("primary_outcome",),
    )


def main() -> None:
    """Run a compact mechanical-design workflow through the umbrella stack."""
    problem_packet = dr.experiments.resolve_problem(DEMO_PROBLEM_ID)
    stack = {
        "agents": dr.agents.__name__,
        "analysis": dr.analysis.__name__,
        "experiments": dr.experiments.__name__,
        "problems": dr.problems.__name__,
    }
    for name, module_name in stack.items():
        print(f"{name} -> {module_name}")

    print("Mechanical benchmark shortlist:")
    for problem_id in MECHANICAL_PROBLEM_IDS:
        print(f"- {_problem_summary(problem_id)}")

    study = _build_study()
    conditions = dr.experiments.build_design(study)
    run_results = dr.experiments.run_study(
        study,
        conditions=conditions,
        agent_factories=dr.experiments.make_seeded_random_baseline_factories(),
        problem_registry={DEMO_PROBLEM_ID: problem_packet},
    )
    exported_paths = dr.experiments.export_analysis_tables(
        study,
        conditions=conditions,
        run_results=run_results,
        output_dir=study.output_dir / "analysis",
        validate_with_analysis_package=True,
    )

    with exported_paths["events.csv"].open("r", encoding="utf-8", newline="") as file_obj:
        event_rows = list(csv.DictReader(file_obj))
    report = dr.analysis.validate_unified_table(dr.analysis.coerce_unified_table(event_rows))

    print("Study builder:", type(study).__name__)
    print("Study problem:", DEMO_PROBLEM_ID)
    print("Agent:", study.agent_specs[0])
    print("Runs:", len(run_results), f"({run_results[0].status.value})")
    print("Primary outcome:", run_results[0].metrics.get("primary_outcome"))
    print("Event rows valid:", report.is_valid, f"(rows={report.n_rows})")
    print("Exported artifacts:", ", ".join(path.name for path in exported_paths.values()))


if __name__ == "__main__":
    main()
